# Generated by Django 3.1.5 on 2021-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
