# Generated by Django 3.1.5 on 2021-08-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0003_auto_20210806_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/profiles-images/default.svg', null=True, upload_to='static/profiles-images/'),
        ),
    ]
