# Generated by Django 3.1.5 on 2021-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0004_auto_20210806_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
