# Generated by Django 3.1.5 on 2021-08-08 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_main', '0007_auto_20210807_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('msg', models.CharField(max_length=1000)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgFromUser', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgToUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
