# Generated by Django 3.1.5 on 2021-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
