# Generated by Django 3.1.5 on 2021-08-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0009_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='msgs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgs', to='chat_main.message'),
        ),
    ]
