# Generated by Django 3.1.5 on 2021-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0010_profile_msgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='msgs',
        ),
        migrations.AddField(
            model_name='profile',
            name='msgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='msgs', to='chat_main.Message'),
        ),
    ]
