# Generated by Django 3.1.5 on 2021-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0011_auto_20210808_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
