# Generated by Django 3.1.5 on 2021-08-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0013_message_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
