# Generated by Django 3.1.5 on 2021-08-16 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_main', '0014_auto_20210810_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_seen', models.BooleanField(default=False)),
                ('msgs', models.ManyToManyField(blank=True, null=True, related_name='unreadmsgs', to='chat_main.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userunmsgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
