# Generated by Django 3.1.5 on 2021-08-19 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_main', '0016_delete_unreadmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('admins', models.ManyToManyField(blank=True, null=True, related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('msgs', models.ManyToManyField(related_name='group_msgs', to='chat_main.Message')),
            ],
        ),
    ]
