# Generated by Django 3.1.5 on 2021-08-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0017_chatgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='msgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_msgs', to='chat_main.Message'),
        ),
    ]
