# Generated by Django 3.1.5 on 2021-08-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0018_auto_20210819_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='img',
            field=models.ImageField(default='static/rooms-images/def.svg', upload_to='static/rooms-images/'),
        ),
    ]
