# Generated by Django 3.1.5 on 2021-08-19 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_main', '0019_chatgroup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='usersIn', to=settings.AUTH_USER_MODEL),
        ),
    ]
