# Generated by Django 3.1.5 on 2021-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0021_auto_20210820_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='msgs',
        ),
        migrations.AddField(
            model_name='msgsroom',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_msgs', to='chat_main.ChatGroup'),
        ),
    ]
