# Generated by Django 3.1.5 on 2021-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0024_auto_20210821_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msgs',
            field=models.ManyToManyField(blank=True, related_name='msgs', to='chat_main.Message'),
        ),
    ]
