# Generated by Django 3.1.5 on 2021-08-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0025_auto_20210821_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgsroom',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/rooms-chat-images/'),
        ),
    ]
